#!/usr/bin/env bash
# This script displays information about subdomains
func1 () {
    line=$(dig "$2"".""$1" | grep -A1 'ANSWER SECTION:' | grep -A1 'IN')
    sub=$(echo "$line" | awk '{ print $1 }' | cut -d '.' -f1)
    rec=$(echo "$line" | awk '{ print $4 }')
    ip=$(echo "$line" | awk '{ print $5 }')
    echo The subdomain "$sub" is a "$rec" record and points to "$ip"
}

func2 () {
    args=("www" "lb-01" "web-01" "web-02")
    for i in "${args[@]}"; do
        line=$(dig "$i"".""$1" | grep -A1 'ANSWER SECTION:' | grep -A1 'IN')
        sub=$(echo "$line" | awk '{ print $1 }' | cut -d '.' -f1)
        rec=$(echo "$line" | awk '{ print $4 }')
        ip=$(echo "$line" | awk '{ print $5 }')
        echo The subdomain "$sub" is a "$rec" record and points to "$ip"
    done
}

if [ "$#" -eq "2" ]; then
    func1 "$1" "$2"
else
    func2 "$1"
fi
