#!/usr/bin/env bash
# Bash script that generates a MySQL dump
if [ $# -eq 0 ]
then
    password=""
else
    password="$1"
fi
mysqldump -u root -p"$password" --all-databases > backup.sql
tar -zcf "$(date '+%d-%m-%Y')".tar.gz backup.sql
