#!/usr/bin/env bash
# This script creates a file containing its PID, displays a text indefinitely,
# Displays a text when receiving a SIGTERM signal. Displays a text when
# receiving a SIGINT signal. Deletes a file and terminates itself when
# receiving a SIGQUIT or SIGTERM signal.

echo $$ >> /var/run/holbertonscript.pid
trap 'echo I hate the kill command && sudo rm /var/run/holbertonscript.pid && kill -9 $$' SIGTERM
trap 'echo Y U no love me?! && sudo rm /var/run/holbertonscript.pid && kill -9 $$' SIGINT SIGQUIT

while :
do
	echo "To infinity and beyond"
	sleep 2
done
