#!/usr/bin/env bash
# This script displays number 1 to 100. At certain iterations will display
# a line of text instead
i=1
while [ $i -le 100 ]
do
	if [ $((i % 15)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
	(( i++ ))
done
