#!/usr/bin/env bash
# This script loops from 1 to 20 and displays text depending on the iteration
i=1
while [ $i -le 20 ]
do
	echo $i
	if [ $i = 4 ]
	then
		echo "bad luck from China"
	elif [ $i = 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i = 17 ]
	then
		echo "bad luck from Italy"
	fi
	(( i++ ))
done
