#!/usr/bin/env bash
# This script loops from 1 to 20 and displays text depending on the iteration
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	(( i++ ))
done
