#!/usr/bin/env bash
# This script redirects to another page
apt-get update
apt-get -y install nginx
echo "Holberton School" > sudo tee usr/share/nginx/html/index.html
service nginx start
redirection="location \/redirect_me \{\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\}"
filename="/etc/nginx/sites-available/default"
sed -i '/^\tserver_name localhost;/a\\n\t'"$redirection"'' $filename
service nginx restart
