#!/usr/bin/env bash
# This script configures Nginx server to have a custom 404 page
apt-get update
apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
redirection="location \/redirect_me \{\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\}"
filename="/etc/nginx/sites-available/default"
sed -i '/^\tserver_name localhost;/a\\n\t'"$redirection"'' $filename
custom="error_page 404 \/custom_404.html;\n\tlocation \/custom_404.html \{\n\t\troot /usr/share/nginx/html;\n\t\tinternal\n\t\}"
sed -i '/^\tserver_name localhost;/ a\\n\t'"$custom"'' $filename
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo service nginx start
