#!/usr/bin/env bash
# This script configures Nginx server to have a custom 404 page
error="error_page 404 \/custom_404.html;\n\tlocation \/custom_404.html \{\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t\}"
file="/etc/nginx/sites-enabled/default"
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/^\tserver_name localhost;/ a\\n\t'"$error"'' $file
sudo service nginx restart
