#!/usr/bin/env bash
# This script configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i "s/^127.*localhost$/127.0.0.2 localhost/" ~/hosts.new
vari="$(grep -Fxq "facebook.com" ~/hosts.new)"
if [ $vari ]
then
    sed -i "s/.*facebook.com$/8.8.8.8 facebook.com/" ~/hosts.new
else
    sed "1i 8.8.8.8 facebook.com" ~/hosts.new
fi
mv -f ~/hosts.new /etc/hosts
