#!/usr/bin/env bash
# Script runs Nginx as the nginx user listening to port 8080.
pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/\<80\>/&80/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
